### ISSUE TITLE
Remove Normal/Expert mode choice

### ISSUE THREAD

**Issue by 153957** [HiSPARC/hisparcdaq#12]
The Normal/Expert Mode choice should be removed, since we just prefer expert mode.
So, leave only the Expert mode.
Also remove the choice dialog when the DAQ starts, since it should default to expert mode.
Likewise, remove the 'Save Settings' button (to save from expert to normal mode).

**Comment by kleiram** [comment]
Removed the choice between normal and expert mode in commit 87ee7d7359bdb84708dbc6fdd86378d6ebede5d3

I haven't removed the save button yet, should it just save to the normal settings now?

**Comment by 153957** [comment]
There should be only one 'Save Settings' button.
Which should save the current settings to a (or the) ini file containing the settings.

(I think) The 'save expert to normal' was meant to save changed made during Expert Mode to Normal Mode.
The normal Save Settings button would save the current settings to the ini of which ever mode you happen to be in.
Only that last button need to remain since we no longer need to copy from expert to normal.

**Comment by 153957** [comment]
Is the 'Expert password' also removed?
I have never used it, and I think we would prefer it if schools did not enter passwords which we do not know.. locking us out..

**Comment by 153957** [comment]
Fixed in v4
