### ISSUE TITLE
Change log (v1 -> v3.0.4)

### ISSUE THREAD

**Issue by 153957** [HiSPARC/hisparcdaq#25]
Version history (v1 - v3.0.4)

```
HiSPARC II: 
v1             LabVIEW 7.1    01-09-2006  Erik Lascaris         not stable

v2.0.0         LabView 7.1    14-01-2008  Jeroen van Leerdam 
v2.0.1         LabView 7.1    15-01-2008  Jeroen van Leerdam    two bugfixes
v2.0.2         LabView 7.1    23-01-2008  Jeroen van Leerdam    two bugfixes, four minor changes
v2.0.3 pre1    LabView 7.1    05-02-2008  Jeroen van Leerdam    three bugfixes, four minor changes, with database error test
v2.0.3         LabView 7.1    05-02-2008  Jeroen van Leerdam    changes pre1 + doesn't write the timestamp in database anymore
v2.1.0         LabView 7.1    10-03-2008  Jeroen van Leerdam    three bugfixes, four minor changes, password for
                                                                "expert mode", button to write "expert settings" to
                                                                "normal settings" file, removed -2.5 ns offset in event time
v2.1.1         LabVIEW 7.1    02-04-2008  Jeroen van Leerdam    one bugfix, front panel window resizable, max.
                                                                events in queue to 1000

v3.0.0-v3.0.2  LabVIEW 8.2    13-11-2009  Pieter van der Deijl  major changes in both the code and the front panel
v3.0.3         LabVIEW 8.2    16-11-2009  Jeroen van Leerdam    moved 3 of the 4 ini files to persistent\configuration directory
v3.0.4         LabVIEW 8.2    03-12-2009  Jeroen van Leerdam    temporarily switched off processing of "comparator data" to work around a bug

HiSPARC III:  
v1.0.0         LabVIEW 8.6.1  04-11-2011  Jeroen van Leerdam    v3.0.4 + programming FPGA and alignment for HiSIII
```

**Comment by 153957** [comment]
I have the source code of some of these previous/intermediate versions available (IIv2.1.1, IIv3.0.4, and IIIv1.0.0). Should those be 'added' to the history? Im not certain if the commits in this repository are used in the new v4.x of the DAQ.. I suggest a new clean master branch is created with the source of the versions for which we have the sources. And then go from there... or not since LabView is really fit for git anyway...

**Comment by davidfokkema** [comment]
Or maybe a new branch 'historic' with the 'new' commits, and leave master as is?

**Comment by 153957** [comment]
That might be a good idea. Im just not certain if the current version of LabView contains any of the improvements from the commits in the master branch. The stuff by Jorian (new-life branch) was incorporated, though Im not certain if his actual commits where used, or if Bob used a different version as base..

**Comment by davidfokkema** [comment]
And no way to figure it out using git, I guess. You can't diff the files, right?

**Comment by 153957** [comment]
Indeed, with LabView being proprietary and all. LabView does have some 'Compare VIs' option.
But I don't think anyone wants to take the time to go through that. I guess Bob knows what he based v4 on. It would be nice to have the old versions in here in case we ever need to check when some important changes were made..

**Comment by 153957** [comment]
Not that important.
