### ISSUE TITLE
1 second offset in timestamps

### ISSUE THREAD

**Issue by 153957** [HiSPARC/hisparcdaq#26]
Somewhere in the LabView code a 1 second offset (actual timestamp + 1s) is introduced.
The reason is not clear yet, nor when this was added (which data is affected).

See HiSPARC/pysparc#22

**Comment by 153957** [comment]
This +1 is required due to the order of things.
See https://github.com/HiSPARC/firmware/issues/2#issuecomment-181399798

**Comment by davidfokkema** [comment]
+1 for DS9 reference 😀
