### ISSUE TITLE
Free LabView editor now available

### ISSUE THREAD

**Issue by 153957** [HiSPARC/hisparcdaq#29]
See https://www.ni.com/en-gb/shop/labview/select-edition/labview-community-edition.html for the free LabView community edition. This can be used to view/edit the HiSPARC DAQ source code.

**Comment by davidfokkema** [comment]
That is very nice! However,

>You may not use the Software for teaching or research at a degree-granting educational institution.

So use with care. Since Nikhef has a license, all teachers and students working at Nikhef can use that license. And all external people can use the community edition, I guess. Cool!

**Comment by 153957** [comment]
And unfortunately the source code (source binaries) in this repo is outdated.. but at least they can now be inspected by practically anyone.

We can add the link to a README in this repo, but it would be nice if the source was also updated..
