### ISSUE TITLE
Window frame has no bounds

### ISSUE THREAD

**Issue by 153957** [HiSPARC/hisparcdaq#3]
The DAQ interface can be scrolled to be entirely out of the window frame.
The window should be not able to scroll beyond the size of the DAQ interface.

**Comment by kleiram** [comment]
As far as I can find, it is not possible to set limits on this...

**Comment by 153957** [comment]
That would be unfortunate, it is very frustrating to work on remote pc with small screens.

Does this help?
http://zone.ni.com/reference/en-XX/help/371361E-01/lvdialog/window_run_time_position/

**Comment by kleiram** [comment]
That only makes it possible to change the minimum size...and we're having issues with the maximum window size.

**Comment by 153957** [comment]
http://www.ni.com/white-paper/7324/en#140555_by_Category

**Comment by 153957** [comment]
Can be fixed in LabView 2012, this has also been fixed for the weatherdaq

**Comment by 153957** [comment]
Fixed in latest versions (v4, using LabView 2014)
