### ISSUE TITLE
Writing log messages to a file

### ISSUE THREAD

**Issue by kleiram** [HiSPARC/hisparcdaq#7]
It would be useful if log messages are written to a log file so there's no need to work with screenshots.

**Comment by davidfokkema** [comment]
But they are, I believe. In any case, they are uploaded to the server. Maybe you should open a feature request on HiSPARC/publicdb and add a reference below.  The request should ask for a method to view the error log files. If you need real-time information, that won't help you. You can ask Jeroen if there _is_ an error log on disk.

**Comment by kleiram** [comment]
Issue closed since it's a duplicate of #1
